import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import NavBar from "./(components)/NavBar/NavBar";
import Landing from "./(components)/Landing/Landing";
import SocialLinks from "./(components)/SocialLinks/SocialLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Ahmed Ramadan (Portfolio)</title>
      </head>
      <body className={`${inter.className} parent`}>
        <Landing>
          <SocialLinks />
          <div className="container mx-auto px-5 md:px-14">{children}</div>
          <NavBar />
        </Landing>
      </body>
    </html>
  );
}
